version: '3.8'

services:
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      # Mount source code for hot reloading
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
      - CHOKIDAR_USEPOLLING=true
      # Backend API URL for development
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    stdin_open: true
    tty: true
    restart: unless-stopped
    networks:
      - mltc-network

networks:
  mltc-network:
    external: true 